from sqlalchemy import Column, String, DateTime, Enum as SAEnum, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
import enum
from ..core.database import Base


class MachineStatus(str, enum.Enum):
    online = "online"
    offline = "offline"
    imaging = "imaging"
    error = "error"


class Machine(Base):
    __tablename__ = "machines"

    id = Column(String, primary_key=True)          # UUID generated by agent on first run
    hostname = Column(String, nullable=False)
    ip_address = Column(String)
    mac_address = Column(String)
    os_version = Column(String)
    cpu = Column(String)
    ram_gb = Column(String)
    disk_info = Column(String)                     # JSON string of disk layout
    status = Column(SAEnum(MachineStatus), default=MachineStatus.offline)
    last_seen = Column(DateTime, default=datetime.utcnow)
    registered_at = Column(DateTime, default=datetime.utcnow)
    agent_version = Column(String)
    notes = Column(String)
    group_id = Column(String, ForeignKey("machine_groups.id", ondelete="SET NULL"))

    jobs = relationship("Job", back_populates="machine", cascade="all, delete-orphan", foreign_keys="Job.machine_id")
    group = relationship("MachineGroup", back_populates="machines")
